var place = "Karachi";
console.log("Is place='Karachi'? | predict True");
console.log(place == 'Karachi');
var number = 24;
console.log("Is number=24 ? | predict False");
console.log(number == 23);
var language = 'Urdu';
console.log("Is language='English' ? | predict False");
console.log(language == 'English');
var country = 'Pakistan';
console.log("Is country='Nairobi ? | predict False");
console.log(country == 'Nairobi');
var tree = 'Hubiscus';
console.log("Is tree='Hubiscus' ? | predict False");
console.log(tree == 'Neem');
var city = 'Washington';
console.log("Is city='Washington' ? | predict False");
console.log(city == 'washington');
var chocolate = 'Kit Kat';
console.log("Is chocolate='Kit Kat' ? | predict True");
console.log(chocolate == 'Kit Kat');
var channel = 'BBC';
console.log("Is channel='BBC' ? | predict True");
console.log(channel == 'BBC');
var stadium = 'SCG';
console.log("Is stadium='SCG' ? | predict False");
console.log(stadium == 'MCG');
var title = 'Conspiracy Theory';
console.log("Is title='Conspiracy Theory' ? | predict True");
console.log(title == 'Conspiracy Theory');
var color = 'Blue';
console.log("Is color='Blue' ? | predict True");
console.log(color == 'Blue');
var section = 'C';
console.log("Is section='C' ? | predict True");
console.log(section == 'C');
